### PR TITLE
Allow flexible Boost versions

### PR DESCRIPTION
**Pull request by AntoinePrv**

### CODE REVIEW

**Comment by ambros-gleixner** [comment]
@ju-manns Can you comment here?

**Comment by ju-manns** [comment]
That change looks very sensible. I will create an internal merge request for that. Thank you!

**Comment by AntoinePrv** [comment]
@ju-manns Any update on this? If this is internally merged, could you cut a bugfix release to integrate the change?

**Comment by leoneifler** [comment]
Sorry that there has been no activity here for so long, I think it got lost in the no-one-feels-responsible limbo. I think this change just effectively removes the minimum version requirements, since it sets the minimum version to whatever version is available. Am I misunderstanding something here?

**Comment by leoneifler** [comment]
Ah, now I understand, I did not see that your change was to the config file. This really is a necessary version requirement, and it is also stated in `CMakeLists.txt`, also the two versions do not match and you are right that it should be propagated from `CMakeLists.txt

**Pull request closed without merging**
